spja_project/urls.py
from django.contrib import admin
from django.urls import path, include

import twitter.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', twitter.views.index, name='index'),
    path('register/', twitter.views.register, name='register'),
    path('settings/', twitter.views.settings, name='settings'),
    path('people/', twitter.views.people, name='people'),
    path('post_tweet/', twitter.views.post_tweet, name='post_tweet'),
    path('delete_tweet/<int:tweet_id>', twitter.views.delete_tweet, name='delete_tweet'),
    path('<str:username>', twitter.views.profile, name='profile'),
    path('follow_user/<str:username>', twitter.views.follow_user, name='follow_user'),
]

twitter/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

import textwrap


class User(AbstractUser):
    username = models.CharField(max_length=30, unique=True)
    full_name = models.CharField(max_length=100)

    def __str__(self):
        return self.username

    def tag(self):
        return f'@{self.username}'

    def short_date_joined(self):
        return self.date_joined.strftime('%B %Y')

    def following_count(self):
        return self.following.count()

    def tweet_count(self):
        return self.tweets.count()


class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='tweets')
    body = models.TextField()
    date = models.DateTimeField('date tweeted', auto_now_add=True)

    def __str__(self):
        body = textwrap.shorten(self.body, width=30, placeholder='...')
        return f'{self.user.tag()}: {body}'

    def short_date(self):
        now = timezone.now()
        delta = now - self.date
        if self.date.year < now.year:
            # Tweet from previous year
            # Example: Jan 1 2017
            return '{0:%b} {0.day} {0.year}'.format(self.date)
        elif delta.total_seconds() < 3600:
            # Posted less than an hour ago
            # Example: 20m
            return f'{round(delta.seconds / 60)}m'
        elif delta.days <= 0:
            # Posted less than 24 hours ago
            # Example: 15h
            return f'{round(delta.seconds / 3600)}h'
        else:
            # Tweet from this year
            # Example: Jan 1
            return '{0:%b} {0.day}'.format(self.date)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(null=True, blank=True)
    followers = models.ManyToManyField(User, related_name='following')

    def __str__(self):
        return f"{self.user}'s profile"

    def follower_count(self):
        return self.followers.count()

twitter/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User, Tweet


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'full_name')


class UpdateUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'full_name')


class PostTweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        exclude = ('user',)
        widgets = {
            'body': forms.Textarea(attrs={
                'cols': 60,
                'rows': 4,
                'placeholder': "What's happening?",
            })
        }
        labels = {
            'body': '',
        }

twitter/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count

from .models import User, Tweet, Profile
from .forms import RegisterUserForm, PostTweetForm


# Registration
def register(request):
    # handle registration
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Create profile for user
            profile = Profile(user=user)
            profile.save()
            return redirect('login')
    else:
        form = RegisterUserForm()
    # render view
    context = {
        'form': form,
    }
    return render(request, 'registration/register.html', context)


# Main views
def index(request):
    if not request.user.is_authenticated:
        # render 'welcome' view for guests
        return render(request, 'twitter/welcome.html')
    # Get tweets from followed users and currently logged in user
    tweets = Tweet.objects.filter(
            Q(user__in=request.user.following.values('user'))
            | Q(user=request.user)
        ).order_by('-date')

    context = {
        'post_tweet_form': PostTweetForm(),
        'tweets': tweets,
    }
    return render(request, 'twitter/index.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    tweets = profile.user.tweets.order_by('-date')
    context = {
        'profile': profile,
        'tweets': tweets,
    }

    if request.user.is_authenticated:
        context['is_following'] = bool(request.user.following.filter(user=user))
    return render(request, 'twitter/profile.html', context)


def people(request):
    # default list
    context = {
        'people': Profile.objects.all()
    }

    if request.GET.get('followed_by'):
        # people followed by <user>
        user = get_object_or_404(User, username=request.GET['followed_by'])
        context['custom_title'] = f'People followed by {user.full_name}'
        context['people'] = user.following.all()
    elif request.GET.get('following'):
        # people following <user>
        user = get_object_or_404(User, username=request.GET['following'])
        context['custom_title'] = f'People following {user.full_name}'
        context['people'] = Profile.objects.filter(
                                user__in=user.profile.followers.all())

    # order all people by their follower count
    context['people'] = context['people']\
        .annotate(num_followers=Count('followers'))\
        .order_by('-num_followers', 'user__full_name')
    return render(request, 'twitter/people.html', context)


@login_required
def settings(request):
    msg = ''
    # update account
    if request.method == 'POST':
        full_name = request.POST.get('full_name', '')
        about = request.POST.get('about', '')
        if not 0 < len(full_name) <= 100:
            msg = 'Error: Full name is required can be at most 100 characters long.'
        else:
            user = request.user
            user.full_name = full_name
            user.profile.about = about
            user.save()
            user.profile.save()
            msg = 'Changes saved.'

    # render view
    context = {
        'form_username': request.user.username,
        'form_full_name': request.user.full_name or '',
        'form_about': request.user.profile.about or '',
        'form_message': msg,
    }
    return render(request, 'twitter/settings.html', context)


# Actions
@login_required
def post_tweet(request):
    if request.method == 'POST':
        tweet_form = PostTweetForm(request.POST)
        if tweet_form.is_valid():
            tweet_body = tweet_form.cleaned_data['body']
            tweet = Tweet(user=request.user, body=tweet_body)
            tweet.save()
            return redirect('index')


@login_required
def delete_tweet(request, tweet_id):
    tweet = Tweet.objects.get(pk=tweet_id)
    tweet.delete()
    # return to previous page
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def follow_user(request, username):
    user = get_object_or_404(User, username=username)
    # follow or unfollow user
    if request.user.following.filter(user=user):
        request.user.following.remove(user.profile)
    else:
        request.user.following.add(user.profile)
    # return to previous page
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

templates/twitter/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}Twitter{% endblock %}</title>
</head>
<body>
    <header>
    {% block header %}
    {% if user.is_authenticated %}
        <p>{% include 'twitter/user_link.html' with u=user %}</p>
    {% endif %}
    {% endblock header %}
    </header>

    <nav>
    {% block nav %}
        <a href="{% url 'index' %}">HOME</a>
        {% if user.is_authenticated %}
            |
            <a href="{% url 'profile' user.username %}">PROFILE</a>
            |
            <a href="{% url 'settings' %}">SETTINGS</a>
            {% if user.is_staff %}
                |
                <a href="{% url 'admin:index' %}">ADMIN</a>
            {% endif %}
            |
            <a href="{% url 'people'%}">PEOPLE</a>
            |
            <a href="{% url 'logout' %}">LOG OUT</a>
        {% else %}
            |
            <a href="{% url 'people' %}">PEOPLE</a>
            |
            <a href="{% url 'login' %}">LOG IN</a>
            |
            <a href="{% url 'register' %}">REGISTER</a>
        {% endif %}
    {% endblock %}
    </nav>

    <hr>

    <div>
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

templates/twitter/index.html
{% extends 'twitter/base.html' %}

{% block content %}
<!-- Post tweet -->
<form action="{% url 'post_tweet' %}" method="post">
    {% csrf_token %}
    {{ post_tweet_form.as_p }}
    <button type="submit">Tweet</button>
</form>

<hr>
<!-- Tweets from followed users -->
<ul>
{% for tweet in tweets %}
    {% include 'twitter/tweet.html' %}
{% endfor %}
</ul>
{% endblock content %}

templates/twitter/people.html
{% extends 'twitter/base.html' %}

{% block title %}
Twitter / People
{% endblock title %}

{% block header %}
{% if not user.is_authenticated %}
    <h2>Discover new people on Twitter</h2>
{% else %}
    {{ block.super }}
{% endif %}
{% endblock header %}

{% block content %}
<h2>
{% if custom_title %}
    {{ custom_title }}
{% else %}
    People on Twitter
{% endif %}
</h2>

<ol>
{% for profile in people %}
<li>
    <p>
        {% include 'twitter/user_link.html' with u=profile.user %}
        &bull;
        <a href="{% url 'people' %}?following={{ profile.user.username }}">Followers: {{ profile.follower_count }}</a>
        {% if profile.about %}
            <br>
            {{ profile.about }}
        {% endif %}
    </p>
</li>
{% endfor %}
</ol>
{% endblock content %}

templates/twitter/profile.html
{% extends 'twitter/base.html' %}

{% block title %}
{{ profile.user.full_name }} ({{ profile.user.tag }}) | Twitter
{% endblock title %}

{% block content %}
<!-- Profile info -->
<p><strong>{{ profile.user.full_name }}</strong></p>
{% if profile.about %}
    <p>{{ profile.about }}</p>
{% endif %}
<p><em title="{{ profile.user.date_joined }}">Joined {{ profile.user.short_date_joined }}</em></p>

<p>
Tweets: {{ profile.user.tweet_count }}
|
<a href="{% url 'people' %}?followed_by={{ profile.user.username }}">Following: {{ profile.user.following_count }}</a>
|
<a href="{% url 'people' %}?following={{ profile.user.username }}">Followers: {{ profile.follower_count }}</a>
</p>

<!-- Actions -->
{% if user.is_authenticated and profile.user != user %}
    <a href="{% url 'follow_user' profile.user.username %}">
    {% if is_following %}Unfollow{% else %}Follow{% endif %}
    </a>
{% endif %}

<hr>
<!-- User tweets -->
<ul>
{% for tweet in tweets %}
    {% include 'twitter/tweet.html' %}
{% endfor %}
</ul>
{% endblock content %}

templates/twitter/settings.html
{% extends 'twitter/base.html' %}

{% block title %}
Twitter / Settings
{% endblock title %}

{% block content %}
<h2>Account settings</h2>
{% if form_message %}
<p><em>{{ form_message }}</em></p>
{% endif %}
<form action="{% url 'settings' %}" method="post">
    {% csrf_token %}
    <p>
        <label for="id_username">Username:</label>
        <input type="text" name="username" id="id_username" value="{{ form_username }}" disabled>
    </p>
    <p>
        <label for="id_full_name">Full name:</label>
        <input type="text" name="full_name" id="id_full_name" maxlength="100" value="{{ form_full_name }}" autofocus required>
    </p>
    <p>
        <label for="id_about">About yourself:</label>
        <br>
        <textarea name="about" id="id_about" cols="30" rows="3">{{ form_about }}</textarea>
    </p>
    <input type="submit" value="Save">
</form>
{% endblock content %}

templates/twitter/tweet.html
<li>
    <p>
        {% include 'twitter/user_link.html' with u=tweet.user %}
        &bull;
        <span title="{{ tweet.date }}">{{ tweet.short_date }}</span>
            {% if tweet.user == user %}
            &bull;
            <a href="{% url 'delete_tweet' tweet.id %}" title="Delete tweet">❌</a>
        {% endif %}
        <br>
        {{ tweet.body }}
    </p>
</li>

templates/twitter/user_link.html
<strong>{{ u.full_name }}</strong>
<a href="{% url 'profile' u.username %}">{{ u.tag }}</a>

templates/twitter/welcome.html
{% extends 'twitter/base.html' %}

{% block header %}
<h2>Welcome to Twitter</h2>
{% endblock header %}

{% block content %}
<p>Please log in or register to continue.</p>
{% endblock content %}